INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (1, 'Wooden Toothbrush', 1, 'Personal Care', 2.99, 0);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (2, 'Hydroflask', 1, 'Outdoor', 10.50, 0);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (3, 'Organic Cotton T-shirt', 2, 'Clothing', 15.99, 100);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (4, 'Bamboo Toothbrush', 1, 'Personal Care', 2.99, 100);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (5, 'Reusable Water Bottle', 1, 'Outdoor', 10.50, 200);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (6, 'Organic Cotton T-shirt', 2, 'Clothing', 15.99, 150);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (7, 'Solar-Powered Lantern', 3, 'Outdoor', 25.00, 50);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (8, 'Recycled Paper Notebook', 4, 'Stationery', 5.50, 120);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (9, 'Energy-Efficient Light Bulb', 5, 'Home Goods', 8.99, 80);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (10, 'Biodegradable Dish Soap', 6, 'Household', 4.49, 180);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (11, 'Fair Trade Coffee Beans', 7, 'Food & Beverages', 12.99, 90);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (12, 'Eco-Friendly Yoga Mat', 8, 'Fitness', 20.00, 60);
INSERT INTO assignment2.Products (ProductID, ProductName, SupplierID, Category, UnitPrice, UnitsInStock) VALUES (13, 'Natural Wood Desk Organizer', 9, 'Office Supplies', 18.75, 100);
